[build]
  # Comando di build che verrà eseguito su Netlify
  command = "bash build.sh"
  
  # Directory che contiene i file da pubblicare
  publish = "."
  
[build.environment]
  # Variabili d'ambiente di build (la chiave vera va nelle impostazioni Netlify)
  NODE_VERSION = "18"

# Redirect rules (opzionale)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
